stages:
  - start-services

start-services:
  stage: start-services
  before_script:
    - cp ${ENV} .env
  script:
    - docker-compose -f docker-compose-start-services.yml up --build -d



# build-fastapi:
#   stage: build
#   before_script:
#     - cp ${ENV} .env
#   script:
#     - docker build -t fastapi-image .

# build-vuejs:
#   stage: build
#   before_script:
#     - cp ${ENV} .env
#   script:
#     - docker build -t vuejs-image -f vuejs/Dockerfile vuejs/
  
# Lint:
#   stage: lint_format
#   script:
#     - docker run --rm fastapi-image ruff check

# Format:
#   stage: lint_format
#   script:
#     - docker run --rm fastapi-image ruff format --check

# Tests:
#   stage: test
#   script:
#     - docker run --rm fastapi-image pytest -s -v

# deploy-job:
#   stage: deploy
#   script:
#     - sudo docker image prune -f && sudo docker-compose up -d