services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/pinterest
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${LOGS_PATH}:${LOGS_PATH}
    depends_on:
      - postgresql
      - redis
      - mongodb
      - mysql

  celery-worker:
    build: .
    container_name: celery-worker-container
    command: "celery -A app.celery.celery_app.celery_instance worker --loglevel=info"
    restart: always
    volumes:
      - .:/pinterest
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${LOGS_PATH}:${LOGS_PATH}
    depends_on:
      - fastapi-app

  celery-beat:
    build: .
    container_name: celery-beat-container
    command: "celery -A app.celery.celery_app.celery_instance beat --loglevel=info"
    restart: always
    volumes:
      - .:/pinterest
      - ${MEDIA_PATH}:${MEDIA_PATH}
      - ${LOGS_PATH}:${LOGS_PATH}
    depends_on:
      - celery-worker

  vuejs-app:
    build:
      context: ./vuejs
      dockerfile: Dockerfile
    container_name: vuejs-container
    ports:
      - "3000:3000"
    volumes:
      - ./vuejs/.:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - fastapi-app